#include "udf.h"
#include "merged_coil_udf.h"

/*
 * SCARFS MergedCoil Fluent UDF
 * Generated by scarfs.coupling.codegen
 *
 * Transport contract:
 *   k=8 UDS scalars transport z = E·((Y_dry - mu)/sigma)  (affine -> conserved-scalar valid).
 *   DEFINE_SOURCE mc_latent_uds_i_source: S_i = rho * omega_Z_i  [kg/m3/s]
 *   DEFINE_ADJUST  mc_manifold_project:   manifold projection + UDM update each iteration
 *   DEFINE_SOURCE  mc_energy_source:      S_h = -absorption_head(z,q) [J/m3/s]
 *
 * UDM layout (see MC_UDM_* macros in header):
 *   [0]  OOD flag  [1] latent-clamp count  [2] energy-clamp count  [3] last S_h
 *   [4 .. 4+k-1]      decoded z_i
 *   [4+k .. 4+k+n_dry-1] decoded Y_i
 *
 * Under-relaxation: urf = min(1.0, MC_URF0 + iter/MC_URF_RAMP_ITERS).
 * Reaches 1.0 at iteration ~400 — never a permanent sub-unity factor.
 *
 * Energy clamp MC_ENERGY_CLAMP = 18300741253.376148 J/m3/s
 * (≈1.3× train max; safety clamp far above signal — does NOT falsify predictions).
 */

/* ---- C-standard utilities (no udf.h dependency in forward-test) ---- */
static double mc_max(double a, double b) { return a > b ? a : b; }
static double mc_min(double a, double b) { return a < b ? a : b; }
static double mc_clamp(double x, double lo, double hi) { return mc_min(mc_max(x, lo), hi); }

/* SiLU(x) = x * sigmoid(x) = x / (1 + exp(-x)) */
static double mc_silu(double x)
{
    return x / (1.0 + exp(-x));
}

/* Stable softplus: log1p(exp(-|x|)) + max(x, 0) */
static double mc_softplus(double x)
{
    return log1p(exp(-fabs(x))) + mc_max(x, 0.0);
}

/* ---- MLP evaluation with LayerNorm support ----
 * Layer type codes in PREFIX_LAYER_TYPES[]:  0 = Linear, 1 = LayerNorm.
 * Linear layers use PREFIX_W[lin_idx] / PREFIX_B[lin_idx] / PREFIX_IN[lin_idx] / PREFIX_OUT[lin_idx].
 * LayerNorm layers use PREFIX_LN_GAMMA[ln_idx] / PREFIX_LN_BETA[ln_idx] / PREFIX_LN_EPS_ARR[ln_idx].
 * Hidden activations: SiLU applied after LayerNorm (or after non-final Linear if no LN present).
 * Final output: linear (no activation).
 */
static void mc_net_eval(
    int n_total_layers,
    const int *layer_types,
    int n_linear,
    const int *lin_in,
    const int *lin_out,
    const double * const *W,
    const double * const *B,
    int n_ln,
    const double * const *ln_gamma,
    const double * const *ln_beta,
    const double *ln_eps,
    const double *x_in,
    double *y_out)
{
    double a[MC_MAX_WIDTH], b_buf[MC_MAX_WIDTH];
    int i, j, l, lin_idx = 0, ln_idx = 0;
    int out_dim = lin_in[0];  /* start with input dim, updated per linear layer */
    for (i = 0; i < lin_in[0]; ++i) a[i] = x_in[i];

    for (l = 0; l < n_total_layers; ++l) {
        if (layer_types[l] == 0) {  /* Linear */
            int ni = lin_in[lin_idx], no = lin_out[lin_idx];
            const double *w = W[lin_idx];
            const double *bb = B[lin_idx];
            int is_last_linear = (lin_idx == n_linear - 1);
            /* Check if next layer is LayerNorm (will handle SiLU activation after it) */
            int next_is_ln = (l + 1 < n_total_layers && layer_types[l + 1] == 1);
            for (i = 0; i < no; ++i) {
                double s = bb[i];
                for (j = 0; j < ni; ++j) s += w[i * ni + j] * a[j];
                /* Apply SiLU here only if: not last linear AND no LayerNorm follows */
                b_buf[i] = (!is_last_linear && !next_is_ln) ? mc_silu(s) : s;
            }
            for (i = 0; i < no; ++i) a[i] = b_buf[i];
            out_dim = no;
            lin_idx++;
        } else {  /* LayerNorm (type == 1) */
            int n = out_dim;
            const double *g = ln_gamma[ln_idx];
            const double *bt = ln_beta[ln_idx];
            double eps_val = ln_eps[ln_idx];
            double mean = 0.0, var = 0.0;
            for (i = 0; i < n; ++i) mean += a[i];
            mean /= mc_max((double)n, 1.0);
            for (i = 0; i < n; ++i) { double d = a[i] - mean; var += d * d; }
            var /= mc_max((double)n, 1.0);
            var = sqrt(mc_max(var + eps_val, 0.0));
            /* After LayerNorm, apply SiLU (hidden activation) */
            for (i = 0; i < n; ++i)
                a[i] = mc_silu((a[i] - mean) / mc_max(var, 1.0e-300) * g[i] + bt[i]);
            ln_idx++;
        }
    }
    for (i = 0; i < out_dim; ++i) y_out[i] = a[i];
}

/* Build standardised thermo features [T, P, 1/T, lnT], clamped to training range */
static void mc_build_q(double T_raw, double P_raw, double *q)
{
    double T = mc_clamp(T_raw, MC_T_TRAIN_MIN, MC_T_TRAIN_MAX);
    double P = mc_clamp(P_raw, MC_P_TRAIN_MIN, MC_P_TRAIN_MAX);
    double feat[4];
    int i;
    feat[0] = T;
    feat[1] = P;
    feat[2] = 1.0 / mc_max(T, 1.0e-300);
    feat[3] = log(mc_max(T, 1.0e-300));
    for (i = 0; i < 4; ++i)
        q[i] = (feat[i] - MC_THERMO_MEAN[i]) / mc_max(MC_THERMO_SCALE[i], 1.0e-300);
}

/* Encode y_std -> z (linear, no bias) */
static void mc_encode(const double *y_std, double *z)
{
    int i, j;
    for (i = 0; i < MC_K; ++i) {
        double s = 0.0;
        for (j = 0; j < MC_N_DRY; ++j) s += MC_ENC_W[i * MC_N_DRY + j] * y_std[j];
        z[i] = s;
    }
#ifdef MC_HAS_ENCMLP
    {  /* residual encoder: z += MLP(y_std) (nonlinear curvature correction) */
        double _e[MC_K]; int _i;
        mc_net_eval(MC_ENCMLP_N_LAYERS, MC_ENCMLP_LAYER_TYPES, MC_ENCMLP_N_LINEAR,
                    MC_ENCMLP_IN, MC_ENCMLP_OUT, MC_ENCMLP_W, MC_ENCMLP_B,
                    MC_ENCMLP_N_LN, MC_ENCMLP_LN_GAMMA, MC_ENCMLP_LN_BETA, MC_ENCMLP_LN_EPS_ARR,
                    y_std, _e);
        for (_i = 0; _i < MC_K; ++_i) z[_i] += _e[_i];
    }
#endif
}

/* Clamp latent to training envelope; returns 1 if any dim was clamped, else 0 */
static int mc_clamp_latent(const double *z_in, double *z_out)
{
    int i, clamped = 0;
    for (i = 0; i < MC_K; ++i) {
        z_out[i] = mc_clamp(z_in[i], MC_LAT_MIN[i], MC_LAT_MAX[i]);
        if (z_out[i] != z_in[i]) clamped = 1;
    }
    return clamped;
}

/* Manifold projection: decode z+q -> y_std -> re-encode -> z_proj */
static void mc_project(const double *z, const double *q, double *z_proj, double *y_std_out)
{
    double zq[MC_K + MC_N_THERMO];
    double y_std[MC_N_DRY];
    int i;
    for (i = 0; i < MC_K; ++i) zq[i] = z[i];
    for (i = 0; i < MC_N_THERMO; ++i) zq[MC_K + i] = q[i];
    mc_net_eval(MC_DEC_N_LAYERS, MC_DEC_LAYER_TYPES, MC_DEC_N_LINEAR,
                MC_DEC_IN, MC_DEC_OUT, MC_DEC_W, MC_DEC_B,
                MC_DEC_N_LN, MC_DEC_LN_GAMMA, MC_DEC_LN_BETA, MC_DEC_LN_EPS_ARR,
                zq, y_std);
    if (y_std_out != NULL)
        for (i = 0; i < MC_N_DRY; ++i) y_std_out[i] = y_std[i];
#ifdef MC_DIRECT_TRANSPORT
    for (i = 0; i < MC_K; ++i) z_proj[i] = z[i];  /* stable latent ODE: NO re-projection; heads read raw z */
#else
    mc_encode(y_std, z_proj);
#endif
}

/* Latent source omega_Z from z_proj + q */
static void mc_latent_source_vec(const double *z_proj, const double *q, double *omega_z)
{
    double zq[MC_K + MC_N_THERMO];
    int i;
    for (i = 0; i < MC_K; ++i) zq[i] = z_proj[i];
    for (i = 0; i < MC_N_THERMO; ++i) zq[MC_K + i] = q[i];
    mc_net_eval(MC_LS_N_LAYERS, MC_LS_LAYER_TYPES, MC_LS_N_LINEAR,
                MC_LS_IN, MC_LS_OUT, MC_LS_W, MC_LS_B,
                MC_LS_N_LN, MC_LS_LN_GAMMA, MC_LS_LN_BETA, MC_LS_LN_EPS_ARR,
                zq, omega_z);
    /* head emits arcsinh(omega_Z / s_Z); physical = sinh(.)*s_Z (clip = overflow guard) */
    for (i = 0; i < MC_K; ++i) {
        double a = omega_z[i];
        if (a > 20.0) a = 20.0;
        if (a < -20.0) a = -20.0;
        omega_z[i] = sinh(a) * MC_LS_ASINH_SCALE[i];
    }
}

/* Absorption head: strictly positive via softplus + calibration */
static double mc_absorption(const double *z_proj, const double *q)
{
    double zq[MC_K + MC_N_THERMO];
    double raw[1];
    int i;
    for (i = 0; i < MC_K; ++i) zq[i] = z_proj[i];
    for (i = 0; i < MC_N_THERMO; ++i) zq[MC_K + i] = q[i];
    mc_net_eval(MC_EN_N_LAYERS, MC_EN_LAYER_TYPES, MC_EN_N_LINEAR,
                MC_EN_IN, MC_EN_OUT, MC_EN_W, MC_EN_B,
                MC_EN_N_LN, MC_EN_LN_GAMMA, MC_EN_LN_BETA, MC_EN_LN_EPS_ARR,
                zq, raw);
    return mc_softplus(raw[0]) * MC_ENERGY_SCALE + MC_ENERGY_FLOOR;
}

/* ---- Rate-derived energy path: S_E = -sum_i h_i(T) * omega_dot_i (first law) ---- */

/* Rate head (scaled arcsinh space) -> physical mass rates rho*dY/dt [kg/m3/s].
 * Inverts the ArcsinhScaler: x = sinh(scaled*std_scale + std_mean) * asinh_scale.
 * The pre-sinh clip at +/-30 is a pure overflow guard (sinh(30)~5e12), not a learning bound. */
static void mc_rates_physical(const double *z_proj, const double *q, double *rates_mass)
{
    double zq[MC_K + MC_N_THERMO];
    double scaled[MC_N_ACTIVE];
    int i;
    for (i = 0; i < MC_K; ++i) zq[i] = z_proj[i];
    for (i = 0; i < MC_N_THERMO; ++i) zq[MC_K + i] = q[i];
    mc_net_eval(MC_RATE_N_LAYERS, MC_RATE_LAYER_TYPES, MC_RATE_N_LINEAR,
                MC_RATE_IN, MC_RATE_OUT, MC_RATE_W, MC_RATE_B,
                MC_RATE_N_LN, MC_RATE_LN_GAMMA, MC_RATE_LN_BETA, MC_RATE_LN_EPS_ARR,
                zq, scaled);
    for (i = 0; i < MC_N_ACTIVE; ++i) {
        double a = scaled[i] * MC_RATE_STD_SCALE[i] + MC_RATE_STD_MEAN[i];
        if (a > 30.0) a = 30.0;
        if (a < -30.0) a = -30.0;
        rates_mass[i] = sinh(a) * MC_RATE_ASINH_SCALE[i];
    }
}

/* NASA7 mass-specific enthalpy h_i(T) [J/kg] for each energy-active species (incl. formation). */
static void mc_h_mass(double T, double *h)
{
    int i;
    double Tt = (T > 1.0e-300) ? T : 1.0e-300;
    double T2 = Tt * Tt, T3 = T2 * Tt, T4 = T3 * Tt;
    for (i = 0; i < MC_N_ACTIVE; ++i) {
        const double *a = (Tt > MC_NASA_TMID[i]) ? &MC_NASA_HIGH[i * 7] : &MC_NASA_LOW[i * 7];
        double h_rt = a[0] + a[1]*Tt/2.0 + a[2]*T2/3.0 + a[3]*T3/4.0 + a[4]*T4/5.0 + a[5]/Tt;
        h[i] = (MC_R_GAS * Tt * h_rt) / MC_MOLAR_MASS[i];
    }
}

/* Rate-derived volumetric absorption [J/m3/s]. No max(0,.) floor: a small negative (exothermic)
 * value at low conversion is physical and must be preserved — only the safety MC_ENERGY_CLAMP
 * bounds the magnitude at the call site. */
static double mc_absorption_from_rates(const double *z_proj, const double *q, double T)
{
    double rates_mass[MC_N_ACTIVE], h[MC_N_ACTIVE];
    double s = 0.0;
    int i;
    mc_rates_physical(z_proj, q, rates_mass);
    mc_h_mass(T, h);
    for (i = 0; i < MC_N_ACTIVE; ++i) s += rates_mass[i] * h[i];
    return s;
}

/* Decode standardised composition to physical mass fractions with closure */
static void mc_decode_composition(const double *z, const double *q, double *Y_out)
{
    double zq[MC_K + MC_N_THERMO];
    double y_std[MC_N_DRY];
    double total;
    int i;
    for (i = 0; i < MC_K; ++i) zq[i] = z[i];
    for (i = 0; i < MC_N_THERMO; ++i) zq[MC_K + i] = q[i];
    mc_net_eval(MC_DEC_N_LAYERS, MC_DEC_LAYER_TYPES, MC_DEC_N_LINEAR,
                MC_DEC_IN, MC_DEC_OUT, MC_DEC_W, MC_DEC_B,
                MC_DEC_N_LN, MC_DEC_LN_GAMMA, MC_DEC_LN_BETA, MC_DEC_LN_EPS_ARR,
                zq, y_std);
    /* Invert linear standardisation: Y = sigma * y_std + mu; clip >= 0 */
    total = 0.0;
    for (i = 0; i < MC_N_DRY; ++i) {
        double y = y_std[i] * MC_COMP_SCALE[i] + MC_COMP_MEAN[i];
        Y_out[i] = mc_max(y, 0.0);
        total += Y_out[i];
    }
    /* H2O = max(1 - sum(Y_retained), 0)  [diluent excluded from encoder] */
    /* Renormalise if retained sum exceeds available non-H2O mass */
    if (total > 1.0) {
        for (i = 0; i < MC_N_DRY; ++i) Y_out[i] = Y_out[i] / mc_max(total, 1.0e-300);
    }
}

/* Read iteration counter from Fluent; gracefully handle unavailability */
static int mc_get_iteration(void)
{
    /* ITERATION macro is Fluent-version-dependent; use RP_Get_Integer if available */
#ifdef CURRENT_TIME_STEP
    return (int)CURRENT_TIME_STEP;
#else
    return 1000;  /* default: URF = 1 after ramp */
#endif
}

/* ---- Fluent hook implementations ---- */

/* DEFINE_ADJUST: manifold projection + UDM update (runs once per iteration, all cells) */
DEFINE_ADJUST(mc_manifold_project, domain)
{
#if !RP_HOST
    Thread *t;
    cell_t c;
    int mc_iter = mc_get_iteration();
    double urf = mc_min(1.0, MC_URF0 + (double)mc_iter / (double)MC_URF_RAMP_ITERS);

    thread_loop_c(t, domain) {
        begin_c_loop(c, t) {
            double z_raw[MC_K], z[MC_K], z_proj[MC_K], y_std[MC_N_DRY], Y[MC_N_DRY];
            double q[MC_N_THERMO];
            double T = C_T(c, t);
            double P = C_P(c, t) + MC_OPERATING_PRESSURE_PA;
            int i, clamped;

            /* Read latent scalars from UDS */
            for (i = 0; i < MC_K; ++i) z_raw[i] = C_UDSI(c, t, i);

            /* Build standardised thermo features (T/P clamped to training range) */
            mc_build_q(T, P, q);

            /* Clamp latent to envelope; flag OOD */
            clamped = mc_clamp_latent(z_raw, z);
            if (clamped) {
                C_UDMI(c, t, MC_UDM_OOD_FLAG) = 1.0;
                C_UDMI(c, t, MC_UDM_LATENT_CLAMP_CNT) += 1.0;
            }

            /* Manifold projection: z_proj = E · decode(z, q) */
            mc_project(z, q, z_proj, y_std);

            /* Apply under-relaxation to the projected latent */
            for (i = 0; i < MC_K; ++i)
                C_UDSI(c, t, i) = (1.0 - urf) * z_raw[i] + urf * z_proj[i];

            /* Decode composition for UDM storage */
            mc_decode_composition(z, q, Y);
            for (i = 0; i < MC_N_DRY; ++i)
                C_UDMI(c, t, MC_UDM_Y_START + i) = Y[i];
            for (i = 0; i < MC_K; ++i)
                C_UDMI(c, t, MC_UDM_Z_START + i) = z[i];

        } end_c_loop(c, t)
    }
#endif
}

/* DEFINE_SOURCE energy: S_h = -absorption recomputed from the rate head + NASA7 (PRIMARY).
 * The distilled softplus head is kept as a UDM cross-check and the out-of-envelope fallback. */
DEFINE_SOURCE(mc_energy_source, c, t, dS, eqn)
{
    double z_raw[MC_K], z[MC_K], z_proj[MC_K], q[MC_N_THERMO];
    double absorption_rate, absorption_head, absorption, sh;
    double T = C_T(c, t);
    double P = C_P(c, t) + MC_OPERATING_PRESSURE_PA;
    int i, ood;

    for (i = 0; i < MC_K; ++i) z_raw[i] = C_UDSI(c, t, i);
    mc_build_q(T, P, q);
    ood = mc_clamp_latent(z_raw, z);
    mc_project(z, q, z_proj, NULL);

    absorption_rate = mc_absorption_from_rates(z_proj, q, T);  /* first-law, true cell T */
    absorption_head = mc_absorption(z_proj, q);                /* cross-check / OOD fallback */
    C_UDMI(c, t, MC_UDM_ABS_HEAD) = absorption_head;

    /* In-envelope: trust the rate-derived path (val R2~0.94). Out-of-envelope (latent clamped):
     * the unbounded rate sum is less trustworthy than the softplus-bounded head, so fall back. */
    absorption = ood ? absorption_head : absorption_rate;
    sh = -absorption;

    if (sh > MC_ENERGY_CLAMP) {
        sh = MC_ENERGY_CLAMP;
        C_UDMI(c, t, MC_UDM_ENERGY_CLAMP_CNT) += 1.0;
    } else if (sh < -MC_ENERGY_CLAMP) {
        sh = -MC_ENERGY_CLAMP;
        C_UDMI(c, t, MC_UDM_ENERGY_CLAMP_CNT) += 1.0;
    }
    C_UDMI(c, t, MC_UDM_LAST_SH) = sh;

    dS[eqn] = 0.0;
    return (real)sh;
}

/* UDS source functions: S_i = rho * omega_Z_i */
static double mc_latent_source(cell_t c, Thread *t, int dim)
{
    double z_raw[MC_K], z[MC_K], z_proj[MC_K], q[MC_N_THERMO], omega_z[MC_K];
    double T = C_T(c, t);
    double P = C_P(c, t) + MC_OPERATING_PRESSURE_PA;
    int i;
    for (i = 0; i < MC_K; ++i) z_raw[i] = C_UDSI(c, t, i);
    mc_build_q(T, P, q);
    mc_clamp_latent(z_raw, z);
    mc_project(z, q, z_proj, NULL);   /* direct: z_proj = clamped z (identity); reproject: E∘D(z) */
    mc_latent_source_vec(z_proj, q, omega_z);
#ifdef MC_DIRECT_TRANSPORT
    /* stable-ODE field f = sinh(ω_Z)·s_Z − β·z (the structural damping that bounds the transport) */
    return C_R(c, t) * (omega_z[dim] - MC_BETA * z[dim]);
#else
    return C_R(c, t) * omega_z[dim];
#endif
}

/* ---- Transport-property head (μ, k, …): state-dependent DEFINE_PROPERTY closures ---- */
static void mc_transport_vec(const double *z_proj, const double *q, double *out)
{
    double zq[MC_K + MC_N_THERMO];
    double raw[MC_N_TRANSPORT];
    int i;
    for (i = 0; i < MC_K; ++i) zq[i] = z_proj[i];
    for (i = 0; i < MC_N_THERMO; ++i) zq[MC_K + i] = q[i];
    mc_net_eval(MC_TP_N_LAYERS, MC_TP_LAYER_TYPES, MC_TP_N_LINEAR,
                MC_TP_IN, MC_TP_OUT, MC_TP_W, MC_TP_B,
                MC_TP_N_LN, MC_TP_LN_GAMMA, MC_TP_LN_BETA, MC_TP_LN_EPS_ARR,
                zq, raw);
    for (i = 0; i < MC_N_TRANSPORT; ++i)
        out[i] = mc_softplus(raw[i]) * MC_TRANSPORT_SCALE[i] + MC_TRANSPORT_FLOOR[i];
}

/* Build the projected latent + thermo features at a cell (shared by the property hooks) */
static void mc_cell_zproj(cell_t c, Thread *t, double *z_proj, double *q)
{
    double z_raw[MC_K], z[MC_K];
    double T = C_T(c, t);
    double P = C_P(c, t) + MC_OPERATING_PRESSURE_PA;
    int i;
    for (i = 0; i < MC_K; ++i) z_raw[i] = C_UDSI(c, t, i);
    mc_build_q(T, P, q);
    mc_clamp_latent(z_raw, z);
    mc_project(z, q, z_proj, NULL);
}

/* DEFINE_PROPERTY: mixture dynamic viscosity [Pa s] (transport head output 0).
 * Hook in Fluent: Materials > <mixture> > Viscosity > user-defined > mc_viscosity. */
DEFINE_PROPERTY(mc_viscosity, c, t)
{
    double z_proj[MC_K], q[MC_N_THERMO], out[MC_N_TRANSPORT];
    mc_cell_zproj(c, t, z_proj, q);
    mc_transport_vec(z_proj, q, out);
    return (real)out[0];
}

/* DEFINE_PROPERTY: mixture thermal conductivity [W/m/K] (transport head output 1).
 * Hook in Fluent: Materials > <mixture> > Thermal Conductivity > user-defined > mc_thermal_conductivity. */
DEFINE_PROPERTY(mc_thermal_conductivity, c, t)
{
    double z_proj[MC_K], q[MC_N_THERMO], out[MC_N_TRANSPORT];
    mc_cell_zproj(c, t, z_proj, q);
    mc_transport_vec(z_proj, q, out);
    return (real)out[1];
}

DEFINE_SOURCE(mc_latent_uds_0_source, c, t, dS, eqn)
{
    dS[eqn] = 0.0;
    return (real)mc_latent_source(c, t, 0);
}
DEFINE_SOURCE(mc_latent_uds_1_source, c, t, dS, eqn)
{
    dS[eqn] = 0.0;
    return (real)mc_latent_source(c, t, 1);
}
DEFINE_SOURCE(mc_latent_uds_2_source, c, t, dS, eqn)
{
    dS[eqn] = 0.0;
    return (real)mc_latent_source(c, t, 2);
}
DEFINE_SOURCE(mc_latent_uds_3_source, c, t, dS, eqn)
{
    dS[eqn] = 0.0;
    return (real)mc_latent_source(c, t, 3);
}
DEFINE_SOURCE(mc_latent_uds_4_source, c, t, dS, eqn)
{
    dS[eqn] = 0.0;
    return (real)mc_latent_source(c, t, 4);
}
DEFINE_SOURCE(mc_latent_uds_5_source, c, t, dS, eqn)
{
    dS[eqn] = 0.0;
    return (real)mc_latent_source(c, t, 5);
}
DEFINE_SOURCE(mc_latent_uds_6_source, c, t, dS, eqn)
{
    dS[eqn] = 0.0;
    return (real)mc_latent_source(c, t, 6);
}
DEFINE_SOURCE(mc_latent_uds_7_source, c, t, dS, eqn)
{
    dS[eqn] = 0.0;
    return (real)mc_latent_source(c, t, 7);
}
